name=MoreDuino
version=0.1.0
author=Toni Homedes i Saun
maintainer=Toni Homedes i Saun <toni@homedes.net>
sentence=Additional core functionality for Arduino.
paragraph=Collection of additional core functionality for Arduino.
category=Other
architectures=*
url=https://github.com/thomedes/MoreDuino
depends=
includes=MoreDuino.h
